[project]
name = "impure-package"
version = "0.1.0"
description = "Add your description here"
authors = []
requires-python = ">=3.13"
dependencies = [
    "ase>=3.26.0",
    "joblib>=1.5.3",
    "numpy>=2.4.0",
    "tqdm>=4.67.1",
]
